// src/app/(introduction)/courses/page.tsx
import type { Metadata } from 'next';
import Image from 'next/image';

import { MainHeading } from '~/components/MainHeading';

const title = 'Courses';

export const metadata: Metadata = { title, openGraph: { title } };

export default function Page() {
  const heading = 'text-xl text-left w-full font-bold mt-8 mb-1';
  const couponLink =
    'https://www.udemy.com/course/nextjs-prisma-graphql-codegen/?couponCode=0721CD7E6ABA8F7ABB7D';
  return (
    <main>
      <MainHeading>Courses</MainHeading>
      <p>
        Udemyで公開中のコースです。以下のリンクから購入すると、クーポンが適用されます。
      </p>
      <h3 className={heading}>
        Next.js、Prisma、GraphQL Code
        Generatorで作るフルスタックWebアプリケーション
      </h3>
      <a href={couponLink} target="_blank" rel="noopener noreferrer">
        <Image
          src="/images/courses/nextjs-prisma-graphql-codegen.png"
          alt="Next.js、Prisma、GraphQL Code Generatorで作るフルスタックWebアプリケーション"
          width="1500"
          height="844"
        />
      </a>
      <p>
        Next.jsをベースとしたモダンなWeb開発の手法について学べます。Prismaの開発者体験の良さや、GraphQL
        Code
        Generatorのコード生成を体感しながら、これらの技術をキャッチアップしていきましょう。
      </p>
      <a href={couponLink} target="_blank" rel="noopener noreferrer">
        👉 コース詳細はこちら 👈
      </a>
    </main>
  );
}

// pages/courses.vue
<template>
  <main>
    <MainHeading>Courses</MainHeading>
    <p
      >Udemyで公開中のコースです。以下のリンクから購入すると、クーポンが適用されます。</p
    >
    <h3 class="heading"
      >Next.js、Prisma、GraphQL Code
      Generatorで作るフルスタックWebアプリケーション</h3
    >
    <a :href="couponLink" target="_blank" rel="noopener noreferrer">
      <img
        src="~/assets/images/courses/nextjs-prisma-graphql-codegen.png"
        alt="Next.js、Prisma、GraphQL Code Generatorで作るフルスタックWebアプリケーション"
        width="1500"
        height="844"
      />
    </a>
    <p
      >Next.jsをベースとしたモダンなWeb開発の手法について学べます。Prismaの開発者体験の良さや、GraphQL
      Code
      Generatorのコード生成を体感しながら、これらの技術をキャッチアップしていきましょう。</p
    >
    <a :href="couponLink" target="_blank" rel="noopener noreferrer">
      👉 コース詳細はこちら 👈
    </a>
  </main>
</template>

<script lang="ts">
import Vue from 'vue'
import { MetaInfo } from 'vue-meta'
import MainHeading from '~/components/MainHeading.vue'

export default Vue.extend({
  components: { MainHeading },
  head(): MetaInfo {
    const title = 'Courses'
    return {
      title,
      meta: [{ hid: 'og:title', property: 'og:title', content: title }],
    }
  },
  computed: {
    couponLink(): string {
      return 'https://www.udemy.com/course/nextjs-prisma-graphql-codegen/?couponCode=FD6CB8BD3CBDC82FC98F'
    },
  },
})
</script>

<style lang="postcss" scoped>
.heading {
  @apply text-xl text-left w-full font-bold mt-8 mb-2;
}
</style>
